demo_bicloo:
    resource: "@DemoBiclooBundle/Resources/config/routing.yml"
    prefix:   /

demo_rest:
    resource: "@DemoRestBundle/Resources/config/routing.yml"
    prefix:   /

demo_test:
    resource: "@DemoTestBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
