services:
    bicloo_manager:
        class: "Demo\BiclooBundle\Bicloo\BiclooManager"
        arguments: [%webservice.carto.url%, %webservice.station.url%, "@doctrine.orm.entity_manager", "@validator"]