<?php

namespace Demo\BiclooBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OccupationDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OccupationDetailRepository extends EntityRepository
{
}
