<?php

namespace Demo\BiclooBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StationRepository extends EntityRepository
{
    
    public function getOrderedStations()
    {
        return $this->createQueryBuilder('s')
                ->orderBy('s.number', 'ASC')
                ->getQuery()
                ->execute();
    }
    
}
