rest_get_one:
    pattern:  /{id}
    defaults: { _controller: DemoRestBundle:Action:getOne }
    requirements:
      _method: GET
      id: \d+
      
rest_get_all:
    pattern:  /
    defaults: { _controller: DemoRestBundle:Action:getAll }
    requirements:
      _method: GET

rest_new:
  pattern: /
  defaults: { _controller: DemoRestBundle:Action:new }
  requirements:
    _method: POST

rest_delete:
    pattern:  /
    defaults: { _controller: DemoRestBundle:Action:delete }
    requirements:
      _method: DELETE