parameters:
#    demo_rest.example.class: Demo\RestBundle\Example

services:
#    demo_rest.example:
#        class: %demo_rest.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
